# Generated by Django 4.1.3 on 2023-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='UserName',
            new_name='username',
        ),
    ]
